addr = ':9292'
# set to true if repo is private
use-ssh-key = false
# size of the cache for page content in MB
page-cache-mb = 1024
# size of the cache for asset content in MB
asset-cache-mb = 1024
# log level: debug, info, warn, error, none
log-level = 'warn'
# secret for update operations
update-secret = ''

# timeout values in seconds
[timeouts]
tail = 30
fetch = 30
reset = 30
lfs = 60
lunr = 30
