addr = ':9292'
ssh-host = 'intermark'
# size of the cache for page content in MB
page-cache-mb = 1024
# size of the cache for asset content in MB
asset-cache-mb = 1024
# log level: debug, info, warn, error, none
log-level = 'debug'

# timeout values in seconds
[timeouts]
tail = 10
fetch = 30
reset = 30
lfs = 60
lunr = 10
